import type { Metadata } from "next";
import "./globals.css";
import { ThemeContextProvider } from "@/context/ThemeContext";
import ThemeProvider from "@/providers/ThemeProvider";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import AuthProvider from "@/providers/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-w-screen overflow-x-hidden">
        <AuthProvider>
          <ThemeContextProvider>
            <ThemeProvider>
              <div
                className="light:bg-bg-light light:text-textColor-light min-h-screen bg-bg text-textColor
                  dark:bg-bg-dark dark:text-textColor-dark"
              >
                <div
                  className="mx-auto flex min-h-screen flex-col max-w-full 2xl:max-w-wrapper-lg
                    xl:max-w-wrapper-md lg:max-w-wrapper-sm md:max-w-wrapper-xs sm:max-w-wrapper-xxs
                    px-base md:px-md"
                >
                  <Navbar />
                  {children}
                  <Footer />
                </div>
              </div>
            </ThemeProvider>
          </ThemeContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
